#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    mobile,         sensorPotentiometer)
#pragma config(Sensor, in2,    bar,            sensorPotentiometer)
#pragma config(Sensor, dgtl1,  elevator,       sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           bar1,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rf,            tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rb,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           lf,            tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port5,           lb,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           goal1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           goal2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           lift1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          bar2,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int reverse = 1;
int half = 1;
int rl=0;
int hl=0;
int sl=0;
task main()
{
clearLCDLine(0);
clearLCDLine(1);
while(true){

		motor[lf] = reverse * (vexRT[Ch3] + reverse*(vexRt[Ch1]+ vexRT[Ch4]))/half;
		motor[lb] = reverse * (vexRT[Ch3] + reverse*(vexRt[Ch1]+ vexRT[Ch4]))/half;
		motor[rf] = reverse * (vexRT[Ch3] - reverse*(vexRt[Ch1]+ vexRT[Ch4]))/half;
		motor[rb] = reverse * (vexRT[Ch3] - reverse*(vexRt[Ch1]+ vexRT[Ch4]))/half;

		motor[goal1] = (127 * vexRt[Btn6U]) + (-127 * vexRT[Btn6D]);
		motor[goal2] = (127 * vexRt[Btn6U]) + (-127 * vexRT[Btn6D]);

		motor[lift1] = (127 * vexRt[Btn5U]) + (-127 * vexRT[Btn5D]);
		motor[lift2] = (127 * vexRt[Btn5U]) + (-127 * vexRT[Btn5D]);

		motor[bar1] = vexRt[Ch2];
		motor[bar2] = vexRt[Ch2];

		if(vexRT[Btn8D]!=rl && rl){
			reverse *= -1;
		}
		rl = vexRT[Btn8D];
		if(vexRT[Btn7D]!=hl && hl){
			half == 1 ? half = 2 : half = 1;
		}
		hl = vexRT[Btn7D];
		if (vexRT[Btn8R]!=sl && sl) {
				SensorValue[solenoid] = !SensorValue[solenoid];
		}
		sl = vexRT[Btn8R];
		displayLCDString(1, 0, "Aut");
	displayLCDNumber(0,0, SensorValue(mobile));
	}



}
